esphome:
  name: wifi-sniffer
  includes:
    - sniffer.h
  on_boot:
    priority: 800
    then:
      - lambda: |-
          sniffer_setup();

interval:
  - interval: 500ms
    then:
      - lambda: |-
          sniffer_loop();
  - interval: 5s
    then:
      - lambda: |-
          sniffer_heartbeat();

esp32:
  board: adafruit_metro_esp32s3
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended

psram:
  mode: octal
  speed: 80MHz

logger:
  level: INFO
  baud_rate: 115200
