esphome:
  name: ble-presence-tracker

esp32:
  board: adafruit_metro_esp32s3
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended

# Essential for the 8MB Octal PSRAM on this board
psram:
  mode: octal
  speed: 80MHz

# Wi-Fi Configuration
wifi:
  ssid: "zvbos"
  password: "97861780838389704195"

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: "Ble-Presence-Tracker Fallback"
    password: "fallbackpassword"

captive_portal:

# Enable logging (INFO level for low overhead)
logger:
  level: INFO

# Enable Home Assistant API (This allows HA to automatically discover the device)
api:

# Enable Over-The-Air updates
ota:
  - platform: esphome
    password: ""

# Enable Bluetooth scanning
esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 320ms
    active: false # Passive scanning is better for dedicated iBeacons, saves RF noise!

# The sensor that natively reports presence to Home Assistant
binary_sensor:
  - platform: ble_presence
    ibeacon_uuid: "426C7565-4368-0302-6D42-6561636F6E73"
    ibeacon_major: 3838
    ibeacon_minor: 4949
    name: "BTC011_pro_zv"
    id: BTC011_pro_zv
    timeout: 15s  # <--- How long to wait before marking "Away"


